### ISSUE TITLE
[ ask Q ]

### ISSUE THREAD

**Issue by neilkuan** [hayao-k/ecr-image-scan-findings-to-slack#1]
May I ask if you are interested, let's integrate this lambda into aws cdk, create a Constructs Library and eventually published to NPM and PyPI. ?!

**Comment by hayao-k** [comment]
Thanks for the great ideas, @guan840912 !
But I'm an AWS CDK newbie.
Do you know of any documentation that might help me to accomplish this?

**Comment by neilkuan** [comment]
We can do this together 😊

**Comment by hayao-k** [comment]
That would be amazing, thank you!

**Comment by neilkuan** [comment]
Let's do it !!! GO GO GO.

**Comment by neilkuan** [comment]
WIP [cdk-ecr-image-scan-notify](https://github.com/hayao-k/cdk-ecr-image-scan-notify).  😊  😊  😊
