### ISSUE TITLE
Minor - URL

### ISSUE THREAD

**Issue by DaneAU** [hayao-k/ecr-image-scan-findings-to-slack#2]
This is a great little script - thanks for sharing it out there.

One thing just noticed is when the URL is generated for the slack notification, it seems to maybe have changed structure slightly. 

`scan_result['repositoryName']}/image/{`

To

`scan_result['repositoryName']}/_/image/{`

Not sure if this is region specific and tested only one one account, just wanted to let you know.

**Comment by hayao-k** [comment]
@DaneAU Thank you!
